live_config_reload = true

[font]
size = 12.0
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
offset = { x = 1, y = 0 }

[env]
term = "xterm-256color"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[scrolling]
history = 100000

[window]
title = "Alacritty"
decorations = "None"
dynamic_padding = true
dynamic_title = true
opacity = 1
dimensions = { columns = 255, lines = 85 }
padding = { x = 0, y = 0 }
option_as_alt = "Both"

# [colors.bright]
# black = '#444b6a'
# red = '#ff7a93'
# green = '#b9f27c'
# yellow = '#ff9e64'
# blue = '#7da6ff'
# magenta = '#bb9af7'
# cyan = '#0db9d7'
# white = '#acb0d0'
#
# [colors.normal]
# black = '#32344a'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#ad8ee6'
# cyan = '#449dab'
# white = '#787c99'
#
# [colors.primary]
# background = '#1a1b26'
# foreground = '#a9b1d6'

# nightfly theme for Alacritty
#
# Upstream: github.com/bluz71/vim-nightfly-colors

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
bright_foreground = "#eeeeee"
foreground = "#bdc1c6"

[colors.selection]
background = "#b2ceee"
text = "#080808"
