live_config_reload = true

[font]
size = 12.0
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
offset = { x = 1, y = 0 }

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[scrolling]
history = 100000

[window]
title = "Alacritty"
decorations = "None"
dynamic_padding = true
dynamic_title = true
opacity = 1
dimensions = { columns = 255, lines = 85 }
padding = { x = 0, y = 0 }
option_as_alt = "Both"

[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'
